### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by kebeleicsaba** [Teaching-projects/SOE-ProgAlap2-BlackJack#1]
Szia! Úgy érzem, hogy a kódom megérettt arra, hogy megnézd. Amit elterveztem azt sikerült megvalósítani. Kérlek nézz rá valamikor. Előre is köszönöm!

**Comment by hegyhati** [comment]
Otos jo lesz? 😆 

Amugy nyilvan vannak kodszervezesi dolgok, amiket picit maskepp csinalnek adott esetben, de szep, komplex, van benne minden.
